### ISSUE TITLE
Может стоит перейти на django?

### ISSUE THREAD

**Issue by dmitryTsatsarin** [lega911/ssp#1]
Если честно, то что ты описываешь похоже на текущую app архитектуру в django с его возможностью быстрого запуска тестов + прикрученные воркеры Celery. Отсюда вопрос, может тебе стоит более внимательно посмотреть на django?

**Comment by lega911** [comment]
Это про другое, просто правила которые можно использовать с любым фреймворком.

**Comment by dmitryTsatsarin** [comment]
Видимо сильно зависит от проекта. Мы аутсорсим в одном стартапе для американцев, и проблема как ни странно не в нагрузке (с этим прекрасно справляется Amazon с автоскейлингом), а в часто меняющийся требованиях и бизнес-флоу, тогда приходится постоянно перекраивать и создавать новые "внутренние микросервисы" частично пересекающиеся со старыми. Поэтому ищу новые подходы, упрощающие/ускоряющие этот процесс. Отметил для себя замечательную идею этого автора:
https://habrahabr.ru/post/316692/#comment_9954262

> ...Далее — об ограничениях языка. При программировании мы как правило упираемся в то что программа разбита на какие то части, каждая хранится в отдельном файле. В нашем случае это рудимент, который мешает программить. Почему? Потому что именно стремление рассовать все по файлам и приладить древовидную структуру приводит нас к модулям и прочему. Оно неплохо само по себе но есть другой путь.
Давайте рассмотрим разработку программы с потоков (flow) — именно так, как ее обычно обсуждают с бизнесом. То есть у нас есть определенные диаграммы состояний и потоков, и вот эти диаграммы с точки зрения приложения, работающего на обмене сообщений — и есть исходный код программы. 
То есть мы задаем агентов, задаем связи между ними, на каждую связь указываем формат сообщения (или он может браться из описания агента) и указываем тип транспорта (вызов метода, tcp, rabbit-agent, да все что угодно) — и компиляем.
И вот тут самый смак. То, что мы сейчас ковыряем и называем исходниками — должно быть результатом компиляции таких диаграмм. То есть это что то вроде DITA — набор кусков кода (описыващих агентов) и набор правил, которые собирают агентов в модули и прикручивают к ним транспорт.
